### PR TITLE
Fetch branches with full refs path

### PR DESCRIPTION
**Pull request by mateherber**
Added full ref paths to several places to avoid collision between tags / branches with shared name

### CODE REVIEW

**Review by lpusok — APPROVED** [review]

**Comment by yojkim** [comment]
I think it has to be optional or fix the bug.
This PR causes build error for me because workflow generates the wrong branch name.

It converts `feature/migration-of-analytics-for-register-process` to `refs/feature/migration-of-analytics-for-register-process` that cannot be fetched.

**Comment by mateherber** [comment]
Hi @yojkim,

Thanks for reporting this, we're going to work on a fix ASAP. I'll let you know of the progress. Until then please use the previous version of the step which should be working fine.

**Comment by yojkim** [comment]
Thank you 👍

**Comment by mateherber** [comment]
Hi @yojkim,

This https://github.com/bitrise-steplib/steps-git-clone/pull/113 should solve your issue. It is just being released with version 4.0.21

Please check when available and report back if it fixed the issue.

Thanks for you patience 👍

**Comment by yojkim** [comment]
Thank you for your quick answer! 👍

**Pull request merged**
